---

# Alpine linux edge APK repo configuration

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

- name: Set /etc/apk/repositories to edge/main, edge/community and edge/testing
  copy:
    src:  files/repositories
    dest: /etc/apk/repositories

- name: Upgrade all installed apk packages to the latest versions
  community.general.apk:
    upgrade: true
    update_cache: true

- name: Reboot the host after apk upgrade
  reboot:
    msg: "Rebooting after apk upgrade"
    connect_timeout: 15
    reboot_timeout: 600
    test_command: whoami

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

