---

- name: Alpine linux preparations
  hosts: controlplane:worker
  gather_facts: true
  roles:
    - role: alpine_latest
    - role: alpine_kernelparams
    - role: alpine_ufw
    - role: alpine_k3s_config
    - role: alpine_k3s_coredns
    - role: alpine_longhorn
