---
- name: Repair GPT on /dev/sda using gdisk and expect
  hosts: storage
  become: yes
  gather_facts: false
  tasks:
    - name: Run gdisk in expect mode to repair GPT
      expect:
        command: gdisk /dev/sda
        responses:
          # When gdisk detects both MBR and a corrupt GPT, it prompts:
          'Found valid MBR and corrupt GPT\. Which do you want to use\?': '2\n'
          # If it asks whether to correct the overlapping/placement issue:
          'Do you want to correct this problem\? \(Y/N\):': 'Y\n'
          # Now, to enter the recovery & transformation menu:
          'Command \(\? for help\)': 'r\n'
          # In the recovery menu, use 'e' to relocate the backup header:
          'Command \(\? for help\)': 'e\n'
          # Then write the changes:
          'Command \(\? for help\)': 'w\n'
      timeout: 300

