---

# Alpine linux kernel parameters configuration

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

- name: Set net forwarding kernel params
  copy:
    dest: /etc/sysctl.d/forwarding.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply kernel parameter changes
  command: /sbin/sysctl -p /etc/sysctl.d/forwarding.conf

- name: Set needed kernel modules in /etc/modules-load.d/k3s.conf
  copy:
    dest: /etc/modules-load.d/k3s.conf
    content: |
      br_netfilter
      iptable_nat
      iptable_filter
      nf_conntrack
      overlay
      dm_crypt
      iscsi_tcp

- name: Install apk packages linux-virt linux-virt-dev
  community.general.apk:
    name: linux-virt,linux-virt-dev
    update_cache: true
    state: present

- name: Modprobe br_netfilter
  command: /sbin/modprobe br_netfilter

- name: Configure cgroups version 2 mode to mount cgroups
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    state: present
    insertafter: '^#rc_cgroup_mode="hybrid"'
    line: rc_cgroup_mode="unified"

- name: Create /etc/cgconfig.conf
  copy:
    dest: /etc/cgconfig.conf
    content: |
      mount {
        cpuacct = /cgroup/cpuacct;
        memory = /cgroup/memory;
        devices = /cgroup/devices;
        freezer = /cgroup/freezer;
        net_cls = /cgroup/net_cls;
        blkio = /cgroup/blkio;
        cpuset = /cgroup/cpuset;
        cpu = /cgroup/cpu;
      }

- name: Modify /etc/update-extlinux.conf
  command: /bin/sed -i 's/default_kernel_opts="pax_nouderef quiet rootfstype=ext4"/default_kernel_opts="pax_nouderef quiet rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"/g' /etc/update-extlinux.conf

- name: Correct /sbin/extlinux reference in /sbin/update-extlinux
  ansible.builtin.lineinfile:
    path: /sbin/update-extlinux
    search_string: 'ext*) extlinux --update /boot || [ -n "$warn_only" ];;'
    line: 'ext*) /sbin/extlinux --update /boot || [ -n "$warn_only" ];;'

- name: Run /sbin/update-extlinux
  command: /sbin/update-extlinux

- name: Reboot the host after kernel parameter changes
  reboot:
    msg: "Rebooting after kernel parameter changes"
    connect_timeout: 15
    reboot_timeout: 600
    test_command: whoami

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

